## Creating Array

In [2]:
import numpy as np
np.__version__

'2.1.2'

### Creating a 1D Array

In [ ]:
arr = np.array([1,2,3])
print(arr)
print("number of dimension: ",arr.ndim)

### Creating a 2D Array

In [ ]:
#arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d = np.array([[1,2,3],[4,5,6]], dtype="str")

print(arr_2d)
print("number of dimension: ",arr_2d.ndim)

### Creating a 3D Array

In [ ]:
arr_3d = np.array ([[[1, 2, 3], [4, 5, 6]],
                      [[7, 8, 9], [10, 11, 12]],
                        [[13, 14, 15], [16, 17, 18]]])
print(arr_3d)
print("number of dimension: ",arr_3d.ndim)

## Array Attributes

In [ ]:
# Checking number of dimension
print(arr_2d.ndim)

# Checking shape of the array
print(arr_2d.shape)

# Checking total number of the elements
print(arr_2d.size)

# Checking data types of elements
print(arr_2d.dtype)


## Indexing

In [ ]:
# Define of numpy array
arr = np.array([1,2,3,4,5])

# Access the first element
print(arr[0])

# Access the third element
print(arr[2])

# Access the last element
print(arr[-1])


In [ ]:
# Define a 2D numpy array
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr_2d)

print("----------")

# Access the first element of the second row
print(arr_2d[0, 0])

# Access the third element of the second row
print(arr_2d[1, 2])

# Access the second element of the last row
print(arr_2d[-1, 1])

# Access the last element of the last row
print(arr_2d[-1, -1])
print(arr_2d[-1, 2])
print(arr_2d[2, -1])

## Slicing

### 1D Array

### 2D Array

In [ ]:
arr_2d = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(arr_2d)

print("-----------------------")

# slicing first 2 rows and 3 columns
print(arr_2d[:2, :3])

print("-----------")

# slicing all rows and last two columns
print(arr_2d[:, -2:])

# all rows and columns
# print(arr_2d[:,:])

print("-----------")

# slicing first row with all elements

## 1D array
print(arr_2d[0, :])
print(arr_2d[0, :].ndim)

## 2D array
print(arr_2d[:1, :])
print(arr_2d[:1, :].ndim)

## Basic Operations

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print(arr1 + arr2)

# Subtraction
print(arr1 - arr2)

# Multiplication
print(arr1 * arr2)

# Division
print(arr2 / arr1)

## Aggregation Functions

In [ ]:
arr1 = np.array([1, 2, 3])

print(arr1.sum())

print(arr1.min())

print(arr1.max())

print(arr1.mean())
print(np.average(arr1))

print(arr1.std())

##### example:

In [ ]:
a = np.array([13, 15, 14, 14, 13])
b = np.array([10, 20, 10, 20, 10])

print(a.mean())
print(b.mean())

print("----------")

print(a.std())
print(b.std())

### Variance

In [ ]:
a = np.array([1, 2, 3])

# Variance
v = a.var()
print(v)

# Standard Deviation
s = np.sqrt(v)
print(s)

sd = a.std()
print(sd)


### Reshaping

In [ ]:
arr = np.array([[1, 2, 3],[4, 5, 6]])

print(arr)
# print(arr.shape)

print("------reshape------")

print(arr.reshape(3, 2))

### Flattering

In [17]:
arr = np.array([[1, 2, 3],[4, 5, 6]])

print(arr)

print("------ravel------")

print(arr.ravel())

[[1 2 3]
 [4 5 6]]
------ravel------
[1 2 3 4 5 6]


## Example: Student Grades

In [ ]:
scores = np.array([
    [13, 14, 13, 17, 20],
    [20, 15, 19, 20, 15],
    [17, 20, 12, 18, 19],
])

print("------flatting------")

flatttened_scores = scores.flatten()
print(flatttened_scores)

print("------reshape------")

reshaped_scores = flatttened_scores.reshape(3, 5)
print(reshaped_scores)